<?php
use App\Http\Controllers\{AuthController,SocialController};use Illuminate\Support\Facades\Route;
Route::middleware('guest')->group(function(){Route::get('/login',[AuthController::class,'loginForm'])->name('login');Route::post('/login',[AuthController::class,'login'])->name('login.submit');Route::get('/register',[AuthController::class,'registerForm'])->name('register');Route::post('/register',[AuthController::class,'register'])->name('register.submit');});
Route::middleware('auth')->group(function(){
Route::get('/',[SocialController::class,'feed'])->name('feed');Route::post('/logout',[AuthController::class,'logout'])->name('logout');
Route::post('/posts',[SocialController::class,'storePost'])->name('posts.store');Route::delete('/posts/{post}',[SocialController::class,'destroyPost'])->name('posts.destroy');Route::post('/posts/{post}/comments',[SocialController::class,'comment'])->name('comments.store');Route::post('/posts/{post}/reaction',[SocialController::class,'react'])->name('reactions.store');Route::post('/posts/{post}/report',[SocialController::class,'report'])->name('reports.store');
Route::get('/friends',[SocialController::class,'friends'])->name('friends');Route::post('/friends/request/{user}',[SocialController::class,'friendRequest'])->name('friends.request');Route::patch('/friends/{friendship}',[SocialController::class,'friendAction'])->name('friends.action');
Route::get('/groups',[SocialController::class,'groups'])->name('groups');Route::post('/groups',[SocialController::class,'createGroup'])->name('groups.store');Route::get('/groups/{group}',[SocialController::class,'group'])->name('groups.show');Route::post('/groups/{group}/join',[SocialController::class,'joinGroup'])->name('groups.join');
Route::get('/messages',[SocialController::class,'messages'])->name('messages');Route::get('/messages/{conversation}',[SocialController::class,'messages'])->name('messages.show');Route::post('/messages/start/{user}',[SocialController::class,'startConversation'])->name('messages.start');Route::post('/messages/{conversation}',[SocialController::class,'sendMessage'])->name('messages.send');
Route::get('/search',[SocialController::class,'search'])->name('search');Route::get('/admin',[SocialController::class,'admin'])->name('admin');Route::patch('/admin/reports/{report}',[SocialController::class,'moderate'])->name('admin.moderate');Route::patch('/admin/users/{user}',[SocialController::class,'toggleUser'])->name('admin.users.toggle');
});
