<?php
namespace App\Http\Controllers;
use App\Models\{Comment,Conversation,Friendship,Group,Message,Post,Reaction,Report,User};use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class SocialController extends Controller{
 private function base():array{$u=auth()->user();$friendIds=Friendship::where('status','accepted')->where(fn($q)=>$q->where('requester_id',$u->id)->orWhere('addressee_id',$u->id))->get()->map(fn($f)=>$f->requester_id===$u->id?$f->addressee_id:$f->requester_id);return['myGroups'=>$u->groups()->take(4)->get(),'pendingCount'=>Friendship::where('addressee_id',$u->id)->where('status','pending')->count(),'messageCount'=>Message::whereHas('conversation.users',fn($q)=>$q->where('users.id',$u->id))->where('user_id','!=',$u->id)->where('created_at','>',now()->subDay())->count(),'contacts'=>User::whereIn('id',$friendIds)->take(6)->get()];}
 public function feed(){ $u=auth()->user();$friendIds=Friendship::where('status','accepted')->where(fn($q)=>$q->where('requester_id',$u->id)->orWhere('addressee_id',$u->id))->get()->map(fn($f)=>$f->requester_id===$u->id?$f->addressee_id:$f->requester_id);$groupIds=$u->groups()->pluck('groups.id');$posts=Post::with(['user','group','reactions','comments.user'])->where(function($q)use($u,$friendIds,$groupIds){$q->where('visibility','college')->orWhere('user_id',$u->id)->orWhere(fn($x)=>$x->where('visibility','friends')->whereIn('user_id',$friendIds))->orWhere(fn($x)=>$x->where('visibility','group')->whereIn('group_id',$groupIds));})->latest()->paginate(8);return view('feed',array_merge($this->base(),['posts'=>$posts,'suggestions'=>User::where('id','!=',$u->id)->inRandomOrder()->take(3)->get()]));}
 public function storePost(Request $r){$data=$r->validate(['content'=>'required_without:media|max:5000','media'=>'nullable|image|max:5120','visibility'=>'required|in:college,friends,group,private','group_id'=>'nullable|exists:groups,id']);if(($data['visibility']==='group')&&!$r->user()->groups()->where('groups.id',$data['group_id']??0)->exists())abort(403);if($r->hasFile('media'))$data['media_path']=$r->file('media')->store('posts','public');$r->user()->posts()->create($data);return back()->with('success','เผยแพร่โพสต์แล้ว');}
 public function destroyPost(Post $post){abort_unless(auth()->id()===$post->user_id||auth()->user()->isAdmin(),403);$post->delete();return back()->with('success','ลบโพสต์แล้ว');}
 public function comment(Request $r,Post $post){$data=$r->validate(['content'=>'required|max:1000','parent_id'=>'nullable|exists:comments,id']);$post->comments()->create($data+['user_id'=>auth()->id()]);return back()->with('success','เพิ่มความคิดเห็นแล้ว');}
 public function react(Request $r,Post $post){$type=$r->validate(['type'=>'required|in:like,love,care,haha,wow,sad'])['type'];$existing=Reaction::where(['post_id'=>$post->id,'user_id'=>auth()->id()])->first();if($existing&&$existing->type===$type)$existing->delete();else Reaction::updateOrCreate(['post_id'=>$post->id,'user_id'=>auth()->id()],['type'=>$type]);return back();}
 public function friends(){ $u=auth()->user();$incoming=Friendship::with('requester')->where('addressee_id',$u->id)->where('status','pending')->get();$accepted=Friendship::with(['requester','addressee'])->where('status','accepted')->where(fn($q)=>$q->where('requester_id',$u->id)->orWhere('addressee_id',$u->id))->get();$related=Friendship::where('requester_id',$u->id)->orWhere('addressee_id',$u->id)->get()->flatMap(fn($f)=>[$f->requester_id,$f->addressee_id])->push($u->id)->unique();$suggestions=User::whereNotIn('id',$related)->take(12)->get();return view('friends',array_merge($this->base(),compact('incoming','accepted','suggestions')));}
 public function friendRequest(User $user){abort_if($user->id===auth()->id(),422);Friendship::firstOrCreate(['requester_id'=>auth()->id(),'addressee_id'=>$user->id],['status'=>'pending']);return back()->with('success','ส่งคำขอเป็นเพื่อนแล้ว');}
 public function friendAction(Request $r,Friendship $friendship){abort_unless($friendship->addressee_id===auth()->id()||$friendship->requester_id===auth()->id(),403);$action=$r->validate(['action'=>'required|in:accept,decline,remove'])['action'];if($action==='accept')$friendship->update(['status'=>'accepted']);else $friendship->delete();return back()->with('success',$action==='accept'?'เพิ่มเป็นเพื่อนแล้ว':'อัปเดตรายชื่อเพื่อนแล้ว');}
 public function groups(){return view('groups',array_merge($this->base(),['groups'=>Group::withCount('members')->latest()->get()]));}
 public function createGroup(Request $r){$data=$r->validate(['name'=>'required|max:120','description'=>'nullable|max:1000','is_private'=>'boolean']);$group=Group::create($data+['owner_id'=>auth()->id()]);$group->members()->attach(auth()->id(),['role'=>'admin']);return redirect()->route('groups.show',$group)->with('success','สร้างกลุ่มแล้ว');}
 public function group(Group $group){if($group->is_private&&!$group->members()->where('users.id',auth()->id())->exists())abort(403);$group->load(['owner','members','posts.user','posts.reactions','posts.comments.user']);return view('group',array_merge($this->base(),compact('group')));}
 public function joinGroup(Group $group){$group->members()->syncWithoutDetaching([auth()->id()=>['role'=>'member']]);return back()->with('success','เข้าร่วมกลุ่มแล้ว');}
 public function messages(?Conversation $conversation=null){$conversations=auth()->user()->conversations()->with(['users','messages'=>fn($q)=>$q->latest()->limit(1)])->get();$conversation=$conversation?->load(['users','messages'=>fn($q)=>$q->oldest()->with('user')])??$conversations->first()?->load(['users','messages'=>fn($q)=>$q->oldest()->with('user')]);if($conversation)abort_unless($conversation->users->contains(auth()->id()),403);return view('messages',array_merge($this->base(),compact('conversations','conversation')));}
 public function startConversation(User $user){$existing=auth()->user()->conversations()->where('is_group',false)->whereHas('users',fn($q)=>$q->where('users.id',$user->id))->first();if(!$existing){$existing=Conversation::create(['is_group'=>false]);$existing->users()->attach([auth()->id(),$user->id]);}return redirect()->route('messages.show',$existing);}
 public function sendMessage(Request $r,Conversation $conversation){abort_unless($conversation->users()->where('users.id',auth()->id())->exists(),403);$data=$r->validate(['body'=>'required|max:3000']);$conversation->messages()->create($data+['user_id'=>auth()->id()]);return back();}
 public function search(Request $r){$term=trim($r->get('q',''));$u=auth()->user();$friendIds=Friendship::where('status','accepted')->where(fn($q)=>$q->where('requester_id',$u->id)->orWhere('addressee_id',$u->id))->get()->map(fn($f)=>$f->requester_id===$u->id?$f->addressee_id:$f->requester_id);$groupIds=$u->groups()->pluck('groups.id');$users=User::where(fn($q)=>$q->where('name','like',"%$term%")->orWhere('department','like',"%$term%"))->take(20)->get();$posts=Post::with(['user','group','reactions','comments.user'])->where('content','like',"%$term%")->where(function($q)use($u,$friendIds,$groupIds){$q->where('visibility','college')->orWhere('user_id',$u->id)->orWhere(fn($x)=>$x->where('visibility','friends')->whereIn('user_id',$friendIds))->orWhere(fn($x)=>$x->where('visibility','group')->whereIn('group_id',$groupIds));})->latest()->take(20)->get();$groups=Group::where('name','like',"%$term%")->where(fn($q)=>$q->where('is_private',false)->orWhereHas('members',fn($x)=>$x->where('users.id',$u->id)))->take(20)->get();return view('search',array_merge($this->base(),compact('term','users','posts','groups')));}
 public function report(Request $r,Post $post){$data=$r->validate(['reason'=>'required|in:spam,harassment,false_information,inappropriate,other','details'=>'nullable|max:1000']);Report::firstOrCreate(['reporter_id'=>auth()->id(),'reportable_type'=>Post::class,'reportable_id'=>$post->id],$data);return back()->with('success','ส่งรายงานให้ผู้ดูแลตรวจสอบแล้ว');}
 public function admin(){abort_unless(auth()->user()->isAdmin(),403);return view('admin',array_merge($this->base(),['reports'=>Report::with(['reporter','reportable'])->latest()->get(),'users'=>User::latest()->get(),'stats'=>['users'=>User::count(),'posts'=>Post::count(),'groups'=>Group::count(),'pending'=>Report::where('status','pending')->count()]]));}
 public function moderate(Request $r,Report $report){abort_unless(auth()->user()->isAdmin(),403);$data=$r->validate(['action'=>'required|in:dismiss,resolve_delete']);DB::transaction(function()use($data,$report){if($data['action']==='resolve_delete')$report->reportable?->delete();$report->update(['status'=>$data['action']==='dismiss'?'dismissed':'resolved','reviewed_by'=>auth()->id()]);});return back()->with('success','ดำเนินการรายงานแล้ว');}
 public function toggleUser(User $user){abort_unless(auth()->user()->isAdmin(),403);abort_if($user->id===auth()->id(),422);$user->update(['is_active'=>!$user->is_active]);return back()->with('success','อัปเดตสถานะสมาชิกแล้ว');}
}
