<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::table('users',function(Blueprint $t){$t->string('student_id')->nullable()->unique();$t->enum('role',['student','teacher','staff','admin'])->default('student');$t->string('department')->nullable();$t->string('avatar')->nullable();$t->boolean('is_active')->default(true);});
Schema::create('groups',function(Blueprint $t){$t->id();$t->foreignId('owner_id')->constrained('users');$t->string('name');$t->text('description')->nullable();$t->boolean('is_private')->default(false);$t->timestamps();});
Schema::create('group_user',function(Blueprint $t){$t->foreignId('group_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->enum('role',['member','moderator','admin'])->default('member');$t->timestamps();$t->primary(['group_id','user_id']);});
Schema::create('posts',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('group_id')->nullable()->constrained()->nullOnDelete();$t->text('content')->nullable();$t->string('media_path')->nullable();$t->enum('visibility',['college','friends','group','private'])->default('college');$t->timestamps();});
Schema::create('comments',function(Blueprint $t){$t->id();$t->foreignId('post_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('parent_id')->nullable()->constrained('comments')->cascadeOnDelete();$t->text('content');$t->timestamps();});
Schema::create('reactions',function(Blueprint $t){$t->id();$t->foreignId('post_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->enum('type',['like','love','care','haha','wow','sad']);$t->timestamps();$t->unique(['post_id','user_id']);});
Schema::create('friendships',function(Blueprint $t){$t->id();$t->foreignId('requester_id')->constrained('users')->cascadeOnDelete();$t->foreignId('addressee_id')->constrained('users')->cascadeOnDelete();$t->enum('status',['pending','accepted','blocked'])->default('pending');$t->timestamps();$t->unique(['requester_id','addressee_id']);});
Schema::create('conversations',function(Blueprint $t){$t->id();$t->string('name')->nullable();$t->boolean('is_group')->default(false);$t->timestamps();});
Schema::create('conversation_user',function(Blueprint $t){$t->foreignId('conversation_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->timestamp('last_read_at')->nullable();$t->primary(['conversation_id','user_id']);});
Schema::create('messages',function(Blueprint $t){$t->id();$t->foreignId('conversation_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->text('body');$t->string('attachment_path')->nullable();$t->timestamps();});
Schema::create('reports',function(Blueprint $t){$t->id();$t->foreignId('reporter_id')->constrained('users');$t->morphs('reportable');$t->string('reason');$t->text('details')->nullable();$t->enum('status',['pending','reviewing','resolved','dismissed'])->default('pending');$t->foreignId('reviewed_by')->nullable()->constrained('users');$t->timestamps();});
}public function down():void{foreach(['reports','messages','conversation_user','conversations','friendships','reactions','comments','posts','group_user','groups'] as $table)Schema::dropIfExists($table);}};
